/*Use ANALYTICS_WH*/

/*SILVER REFRESH TASK*/

CREATE OR REPLACE SCHEMA ECOMMERCE_DB.TASKS;

CREATE OR REPLACE TASK ECOMMERCE_DB.TASKS.SILVER_REFRESH_TASK
WAREHOUSE = ANALYTICS_WH
SCHEDULE = 'USING CRON 0 2 * * * UTC'
AS
BEGIN

CREATE OR REPLACE TABLE ECOMMERCE_DB.SILVER.ORDERS AS
SELECT
    order_id,
    customer_id,
    order_status,
    TO_TIMESTAMP(order_purchase_timestamp) AS order_purchase_ts,
    TO_TIMESTAMP(order_approved_at) AS order_approved_ts,
    TO_TIMESTAMP(order_delivered_carrier_date) AS order_carrier_ts,
    TO_TIMESTAMP(order_delivered_customer_date) AS order_delivered_ts,
    TO_TIMESTAMP(order_estimated_delivery_date) AS order_estimated_delivery_ts
FROM ECOMMERCE_DB.BRONZE.ORDERS_RAW
WHERE order_id IS NOT NULL;

END;


CREATE OR REPLACE TASK ECOMMERCE_DB.TASKS.GOLD_REFRESH_TASK
WAREHOUSE = ANALYTICS_WH
AFTER ECOMMERCE_DB.TASKS.SILVER_REFRESH_TASK
AS
BEGIN

CREATE OR REPLACE TABLE ECOMMERCE_DB.GOLD.DAILY_REVENUE AS
SELECT
    DATE(o.order_purchase_ts) AS order_date,
    SUM(oi.price) AS total_revenue,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM ECOMMERCE_DB.SILVER.ORDERS o
JOIN ECOMMERCE_DB.SILVER.ORDER_ITEMS oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY order_date;

END;


ALTER TASK ECOMMERCE_DB.TASKS.SILVER_REFRESH_TASK SUSPEND;
ALTER TASK ECOMMERCE_DB.TASKS.GOLD_REFRESH_TASK SUSPEND;


ALTER TASK ECOMMERCE_DB.TASKS.SILVER_REFRESH_TASK RESUME;
ALTER TASK ECOMMERCE_DB.TASKS.GOLD_REFRESH_TASK RESUME;

SHOW TASKS IN SCHEMA ECOMMERCE_DB.TASKS;

/*Manually run the SILVER task (which is scheduled at 2 am daily)*/
EXECUTE TASK ECOMMERCE_DB.TASKS.SILVER_REFRESH_TASK;

SELECT *
FROM TABLE(
  INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'ECOMMERCE_DB.TASKS.SILVER_REFRESH_TASK',
    RESULT_LIMIT => 5
  )
);



SELECT *
FROM TABLE(
  INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'ECOMMERCE_DB.TASKS.GOLD_REFRESH_TASK',
    RESULT_LIMIT => 5
  )
);



SELECT * 
FROM ECOMMERCE_DB.GOLD.DAILY_REVENUE
ORDER BY order_date DESC
LIMIT 10;


/*TIME TRAVEL*/

SELECT COUNT(*) 
FROM ECOMMERCE_DB.GOLD.DAILY_REVENUE;


/*CREATE OR REPLACE TABLE ECOMMERCE_DB.GOLD.DAILY_REVENUE AS
SELECT
    DATE(o.order_purchase_ts) AS order_date,
    SUM(oi.price) AS total_revenue,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM ECOMMERCE_DB.SILVER.ORDERS o
JOIN ECOMMERCE_DB.SILVER.ORDER_ITEMS oi
    ON o.order_id = oi.order_id
WHERE o.order_status = 'delivered'
GROUP BY order_date;


    --- Keep this statement as backup in case data gets permanently erased ---
*/

SELECT COUNT(*)
FROM ECOMMERCE_DB.GOLD.DAILY_REVENUE;

SHOW TASKS IN SCHEMA ECOMMERCE_DB.TASKS;

ALTER TASK ECOMMERCE_DB.TASKS.GOLD_REFRESH_TASK SUSPEND;
ALTER TASK ECOMMERCE_DB.TASKS.SILVER_REFRESH_TASK SUSPEND;

SELECT COUNT(*) 
FROM ECOMMERCE_DB.GOLD.DAILY_REVENUE;

DELETE FROM ECOMMERCE_DB.GOLD.DAILY_REVENUE;
/*Accidental Deletion of data*/

SELECT COUNT(*) 
FROM ECOMMERCE_DB.GOLD.DAILY_REVENUE;

SELECT COUNT(*)
FROM ECOMMERCE_DB.GOLD.DAILY_REVENUE
AT (OFFSET => -60);
/*Views the table before 60 sec*/


CREATE OR REPLACE TABLE ECOMMERCE_DB.GOLD.DAILY_REVENUE AS
SELECT *
FROM ECOMMERCE_DB.GOLD.DAILY_REVENUE
AT (OFFSET => -60);
/*Create the table how it was before 60 seconds*/

SELECT COUNT(*) 
FROM ECOMMERCE_DB.GOLD.DAILY_REVENUE;
/*Data retrieved thanks to 'Time Travel'*/

ALTER TASK ECOMMERCE_DB.TASKS.GOLD_REFRESH_TASK RESUME;
ALTER TASK ECOMMERCE_DB.TASKS.SILVER_REFRESH_TASK RESUME;

SHOW TASKS IN SCHEMA ECOMMERCE_DB.TASKS;


/*Zero-Copy Cloning*/

CREATE OR REPLACE TABLE ECOMMERCE_DB.GOLD.DAILY_REVENUE_CLONE
CLONE ECOMMERCE_DB.GOLD.DAILY_REVENUE;
/*Copy of clone created*/

SELECT COUNT(*) FROM ECOMMERCE_DB.GOLD.DAILY_REVENUE_CLONE;
/*Same no. of columns present*/

DELETE FROM ECOMMERCE_DB.GOLD.DAILY_REVENUE_CLONE;


SELECT COUNT(*) FROM ECOMMERCE_DB.GOLD.DAILY_REVENUE;
SELECT COUNT(*) FROM ECOMMERCE_DB.GOLD.DAILY_REVENUE_CLONE;
/*Can see that it is independent table*/

DROP TABLE ECOMMERCE_DB.GOLD.DAILY_REVENUE_CLONE;
/*Optional cleanup*/


/*Data Viz*/

/*Shows how many orders on each day*/
SELECT *
FROM ECOMMERCE_DB.GOLD.DAILY_REVENUE
ORDER BY order_date;

/*KPI view*/
/*Shows the Key Performance Metric as summary*/
CREATE OR REPLACE VIEW ECOMMERCE_DB.GOLD.DAILY_REVENUE_KPI AS
SELECT
    MAX(order_date) AS latest_date,
    SUM(total_revenue) AS total_revenue_to_date,
    SUM(total_orders) AS total_orders_to_date
FROM ECOMMERCE_DB.GOLD.DAILY_REVENUE;


SELECT * FROM ECOMMERCE_DB.GOLD.DAILY_REVENUE_KPI;

/*Customer metrics*/
SELECT
    total_orders,
    COUNT(*) AS customer_count
FROM ECOMMERCE_DB.GOLD.CUSTOMER_METRICS
GROUP BY total_orders
ORDER BY total_orders;

/*Product performance*/
SELECT
    product_id,
    total_revenue
FROM ECOMMERCE_DB.GOLD.PRODUCT_PERFORMANCE
ORDER BY total_revenue DESC
LIMIT 10;

SHOW TABLES IN SCHEMA ECOMMERCE_DB.GOLD;

SELECT *
FROM ECOMMERCE_DB.GOLD.DAILY_REVENUE
LIMIT 10;

GRANT USAGE ON DATABASE ECOMMERCE_DB TO USER FAIZ;

GRANT USAGE ON SCHEMA ECOMMERCE_DB.GOLD TO USER FAIZ;

GRANT SELECT ON TABLE ECOMMERCE_DB.GOLD.DAILY_REVENUE TO USER FAIZ;

GRANT INSERT ON TABLE ECOMMERCE_DB.GOLD.REVENUE_PREDICTIONS TO USER FAIZ;


SHOW GRANTS ON TABLE ECOMMERCE_DB.GOLD.DAILY_REVENUE;
