CREATE TABLE ML_TRAINING_TRIGGER (
    RUN_TIME TIMESTAMP,
    STATUS STRING
);

SHOW TABLES IN ECOMMERCE_DB.TASKS;

/* Task for Automated ML training */ 
CREATE OR REPLACE TASK ML_RETRAIN_TASK
WAREHOUSE = ANALYTICS_WH
SCHEDULE = 'USING CRON 0 2 * * * UTC'
AS


INSERT INTO ECOMMERCE_DB.TASKS.ML_TRAINING_TRIGGER
VALUES (CURRENT_TIMESTAMP(), 'READY');

SELECT * 
FROM ECOMMERCE_DB.TASKS.ML_TRAINING_TRIGGER;

INSERT INTO ECOMMERCE_DB.TASKS.ML_TRAINING_TRIGGER
VALUES (CURRENT_TIMESTAMP(), 'READY');

SELECT * 
FROM ECOMMERCE_DB.TASKS.ML_TRAINING_TRIGGER;


CREATE TABLE MODEL_PERFORMANCE (
    MODEL_NAME STRING,
    R2 FLOAT,
    MAE FLOAT,
    RMSE FLOAT,
    TRAINED_AT TIMESTAMP
);

SELECT * FROM MODEL_PERFORMANCE;
